name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
          - 4571:4571

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install
        run: npm install

      - name: NPM Test
        run: npm test
        env:
          SQS_ENDPOINT: http://localhost:4566
          S3_ENDPOINT: http://localhost:4566

      - name: Wait for Localstack
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: http://localhost:4566/health
          max-attempts: 60
          retry-delay: 5s

      - run: npm run system-test
        env:
          SQS_ENDPOINT: http://localhost:4566
          S3_ENDPOINT: http://localhost:4566
